services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "secret"
    ports:
      - "15432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data 
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com.br"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    ports:
      - "16543:80"
    depends_on:
      - db
